name: Dataverse Solution Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Power Platform CLI
        run: |
          npm install -g @microsoft/powerplatform-cli

      - name: Authenticate with Dataverse
        env:
          CLIENT_ID: ${{ secrets.DATAVERSE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.DATAVERSE_TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.DATAVERSE_CLIENT_SECRET }}
          DATAVERSE_URL: ${{ secrets.DATAVERSE_DEV_URL }}
        run: |
          pac auth create --client-id "$CLIENT_ID" --tenant "$TENANT_ID" --client-secret "$CLIENT_SECRET" --url "$DATAVERSE_URL"

      - name: Export Solution from Dev
        run: |
          pac solution export --name "Permit Management" --path exported_solution.zip --environment "$DATAVERSE_URL"

      - name: Upload Solution Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exported-solution
          path: exported_solution.zip

  import-solution:
    needs: export-solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Solution Artifact
        uses: actions/download-artifact@v3
        with:
          name: exported-solution

      - name: Install Power Platform CLI
        run: |
          npm install -g @microsoft/powerplatform-cli

      - name: Authenticate with Dataverse (Test Environment)
        env:
          CLIENT_ID: ${{ secrets.DATAVERSE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.DATAVERSE_TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.DATAVERSE_CLIENT_SECRET }}
          DATAVERSE_URL: ${{ secrets.DATAVERSE_TEST_URL }}
        run: |
          pac auth create --client-id "$CLIENT_ID" --tenant "$TENANT_ID" --client-secret "$CLIENT_SECRET" --url "$DATAVERSE_URL"

      - name: Import Solution into Test
        run: |
          pac solution import --path exported_solution.zip --environment "$DATAVERSE_URL"
